[package]
name = "todui"
version = "0.1.0"
description = "tui todo"
authors = ["Stephen Beck <2529298+altphi@users.noreply.github.com>"]
license = "MIT"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
ratatui = "0.30.0"
color-eyre = "0.6.3"
dirs = "6"
shellexpand = "3"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
toml = "0.8"
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
tempfile = "3.26.0"
